version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # Default directory for Nginx web files
hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
